### ISSUE TITLE
Cannot start server

### ISSUE THREAD

**Issue by daniellam258** [dnanhkhoa/python-vncorenlp#3]
I'm starting server using this line

> vncorenlp -Xmx2g ../out/VnCoreNLP-1.1.jar -p 9000 -a "wseg"

However, I got this error
`2019-05-04 01.57.19 INFO VnCoreNLPServer - Using annotators: wseg
2019-05-04 01:57:19 INFO  WordSegmenter:24 - Loading Word Segmentation model
2019-05-04 01.57.19 ERROR VnCoreNLPServer - null
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at vncorenlp.VnCoreNLPServer.loadVnCoreNLP(VnCoreNLPServer.java:79)
        at vncorenlp.VnCoreNLPServer.main(VnCoreNLPServer.java:175)
Caused by: java.io.IOException: WordSegmenter: ../out/models/wordsegmenter/wordsegmenter.rdr is not found!
        at vn.corenlp.wordsegmenter.WordSegmenter.<init>(WordSegmenter.java:27)
        at vn.corenlp.wordsegmenter.WordSegmenter.initialize(WordSegmenter.java:34)
        ... 6 more
`

**Comment by daniellam258** [comment]
It's my fault forgetting download the models folder

**Comment by manhnguyenquoc** [comment]
Hi @lhdung258 ,

Could you show me how to start the server please?

I followed the intruction but get the error _'vncorenlp' is not recognized as an internal or external command, operable program or batch file._

I've opened command prompt of Windows and entered `vncorenlp -Xmx2g E:\Data\Projects\MobiFone5\NLP\VnCoreNLP-master\VnCoreNLP-1.1.jar -p 9000 -a "wseg,pos,ner,parse"`  as the image bellow
![error](https://user-images.githubusercontent.com/22399058/62761020-ae6e0600-baaf-11e9-9441-3d1d64793ced.PNG)
