### ISSUE TITLE
Form too large error with VncoreNLPServer

### ISSUE THREAD

**Issue by Avi197** [dnanhkhoa/python-vncorenlp#6]
I got this problem when tokenizing data using vncorenlp python, and it work fine until it reach 1 of the line in the data file.

`org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content
	at org.eclipse.jetty.server.Request.getParameters(Request.java:380)
	at org.eclipse.jetty.server.Request.getParameter(Request.java:1021)
	at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194)
	at spark.Request.queryParams(Request.java:283)
	at spark.http.matching.RequestWrapper.queryParams(RequestWrapper.java:141)
	at vncorenlp.VnCoreNLPServer.handle(VnCoreNLPServer.java:247)
	at vncorenlp.VnCoreNLPServer.lambda$3(VnCoreNLPServer.java:184)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Form too large: 250544 > 200000
	at org.eclipse.jetty.server.Request.extractFormParameters(Request.java:523)
	at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:461)
	at org.eclipse.jetty.server.Request.getParameters(Request.java:376)
`

Best regards

**Comment by dnanhkhoa** [comment]
Thank you for reporting this problem,
Could you please give me more detail to reproduce your trouble? It would be better if you can give me a small sample of your data that caused the problem.
